"""Generate the advisory configuration schema from the reference index (TC-82)."""

import argparse
import copy
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "docs/reference-index.json"
OUTPUT = ROOT / "schema/stm32-config.schema.json"


def optional(schema):
    """Empty values defer to framework defaults; do not invent defaults here."""
    return {"anyOf": [schema, {"enum": [None, "", []]}]}


def object_schema():
    return {"type": "object", "properties": {}, "additionalProperties": True}


def generate(index):
    config = object_schema()
    for option in index["options"]:
        # Explicit metadata: never infer enums by splitting human-readable prose.
        leaf = optional(copy.deepcopy(option["schema"]))
        leaf["description"] = f'{option["requirement"]}: {option["type"]}'
        for path in option["yaml_paths"]:
            node = config
            for part in path[:-1]:
                prop = node["properties"].setdefault(part, optional(object_schema()))
                node = prop["anyOf"][0]
            name = path[-1]
            if name in node["properties"]:
                raise ValueError(f"Duplicate schema path: {path}")
            node["properties"][name] = copy.deepcopy(leaf)
            if option["key"] not in ("profiles", "include"):
                arrays = [s for s in option["schema"].get("anyOf", []) if s.get("type") == "array"]
                node["properties"][name + "_append"] = (
                    optional(copy.deepcopy(arrays[0])) if arrays else {"$ref": "#/$defs/append"})

    def append_rules(node):
        node["patternProperties"] = {"_append$": {"$ref": "#/$defs/append"}}
        for child in node["properties"].values():
            for branch in child.get("anyOf", []):
                if branch.get("type") == "object":
                    append_rules(branch)

    append_rules(config)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": "Generated by python ci/config_schema.py; edit docs/reference-index.json.",
        "title": "stm32-cmake-yml configuration (0.10.0)",
        "description": "Advisory structural validation, not a replacement for CMake Configure.",
        "$ref": "#/$defs/configuration",
        "$defs": {
            "configuration": config,
            "profiles": {
                "type": "object",
                "propertyNames": {"pattern": "^[^_]+$"},
                "additionalProperties": optional({"$ref": "#/$defs/configuration"}),
            },
            "append": optional({"type": "array", "items": {
                "type": ["string", "number", "boolean", "null"]}}),
        },
    }


def render(index):
    return json.dumps(generate(index), ensure_ascii=False, indent=2) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(json.loads(INDEX.read_text(encoding="utf-8")))
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            parser.exit(1, "Schema is stale: run python ci/config_schema.py\n")
        print("PASS: configuration schema matches the reference index")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
