# YAML include and JSON-tree merging (spec 3.8, TC-80).
# Keep types until all files have been merged; flatten only once afterwards.
include_guard(GLOBAL)

# Extract a JSON value without losing string/boolean/null types.
function(_stm32_yml_json_value JSON KEY OUT)
    string(JSON _type TYPE "${JSON}" "${KEY}")
    string(JSON _value GET "${JSON}" "${KEY}")
    if(_type STREQUAL "STRING")
        _stm32_yml_json_quote(_value "${_value}")
    elseif(_type STREQUAL "NULL")
        set(_value "null")
    elseif(_type STREQUAL "BOOLEAN")
        if(_value)
            set(_value "true")
        else()
            set(_value "false")
        endif()
    endif()
    set(${OUT} "${_value}" PARENT_SCOPE)
endfunction()

function(_stm32_yml_json_concat BASE EXTRA OUT)
    set(_result "${BASE}")
    string(JSON _length LENGTH "${EXTRA}")
    string(JSON _next LENGTH "${_result}")
    if(_length GREATER 0)
        math(EXPR _last "${_length} - 1")
        foreach(_index RANGE 0 ${_last})
            _stm32_yml_json_value("${EXTRA}" "${_index}" _item)
            string(JSON _result SET "${_result}" ${_next} "${_item}")
            math(EXPR _next "${_next} + 1")
        endforeach()
    endif()
    set(${OUT} "${_result}" PARENT_SCOPE)
endfunction()

# Objects merge recursively. Replacements precede additions within each file.
# Inside profiles, preserve and accumulate _append for profile activation:
# expanding it now would incorrectly replace the project-level base list.
function(_stm32_yml_merge_json BASE PATCH PATH OUT)
    set(_result "${BASE}")
    string(JSON _count LENGTH "${PATCH}")
    if(_count GREATER 0)
        math(EXPR _last "${_count} - 1")
        foreach(_pass IN ITEMS replace append)
            foreach(_index RANGE 0 ${_last})
                string(JSON _key MEMBER "${PATCH}" ${_index})
                if(_key MATCHES "_append$")
                    if(_pass STREQUAL "replace")
                        continue()
                    endif()
                elseif(_pass STREQUAL "append")
                    continue()
                endif()
                string(JSON _type TYPE "${PATCH}" "${_key}")
                _stm32_yml_json_value("${PATCH}" "${_key}" _value)
                string(JSON _old_type ERROR_VARIABLE _missing TYPE "${_result}" "${_key}")
                set(_path "${PATH}${_key}.")
                if(_pass STREQUAL "append" AND NOT PATH MATCHES "^profiles\\.")
                    string(REGEX REPLACE "_append$" "" _base_key "${_key}")
                    if(_type STREQUAL "NULL" OR _value STREQUAL "\"\"")
                        continue()
                    endif()
                    if(NOT _type STREQUAL "ARRAY")
                        stm32_yml_msg(E013 "${PATH}${_key}")
                    endif()
                    string(JSON _base_type ERROR_VARIABLE _absent TYPE "${_result}" "${_base_key}")
                    if(_absent OR _base_type STREQUAL "NULL")
                        set(_base "[]")
                    else()
                        _stm32_yml_json_value("${_result}" "${_base_key}" _base)
                        if(_base STREQUAL "\"\"")
                            set(_base "[]")
                        elseif(NOT _base_type STREQUAL "ARRAY")
                            stm32_yml_msg(E013 "${PATH}${_base_key}")
                        endif()
                    endif()
                    _stm32_yml_json_concat("${_base}" "${_value}" _value)
                    string(JSON _result SET "${_result}" "${_base_key}" "${_value}")
                else()
                    if(_type STREQUAL "OBJECT")
                        if(_old_type STREQUAL "OBJECT")
                            string(JSON _base GET "${_result}" "${_key}")
                        else()
                            set(_base "{}")
                        endif()
                        _stm32_yml_merge_json("${_base}" "${_value}" "${_path}" _value)
                    elseif(_pass STREQUAL "append" AND _type STREQUAL "ARRAY"
                            AND _old_type STREQUAL "ARRAY")
                        string(JSON _base GET "${_result}" "${_key}")
                        _stm32_yml_json_concat("${_base}" "${_value}" _value)
                    endif()
                    string(JSON _result SET "${_result}" "${_key}" "${_value}")
                endif()
            endforeach()
        endforeach()
    endif()
    set(${OUT} "${_result}" PARENT_SCOPE)
endfunction()

# Pass the accumulated configuration through the depth-first traversal. Do not
# pre-merge an include subtree in isolation: an append-only sibling must see
# values supplied by earlier siblings. The active stack detects cycles, while
# legitimate repeated includes remain ordered operations (spec 3.8.4).
function(_stm32_yml_load_includes FILE BASE STACK OUT)
    get_filename_component(_absolute "${FILE}" ABSOLUTE)
    if(NOT EXISTS "${_absolute}" OR IS_DIRECTORY "${_absolute}")
        set(_chain ${STACK} "${_absolute}")
        list(JOIN _chain " -> " _chain)
        stm32_yml_msg(E010 "${_chain}")
    endif()
    file(REAL_PATH "${_absolute}" _file)
    if(_file IN_LIST STACK)
        set(_chain ${STACK} "${_file}")
        list(JOIN _chain " -> " _chain)
        stm32_yml_msg(E011 "${_chain}")
    endif()
    list(APPEND STACK "${_file}")
    # Both names matter when an include uses a symlink: track file content and
    # the spelled dependency used by the project.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_absolute}" "${_file}")
    # CMake's JSON reader accepts trailing documents. Wrap the complete YAML
    # stream in an array so a second document cannot be silently discarded.
    execute_process(COMMAND "${YQ_EXECUTABLE}" eval-all -o=json "[.]" "${_file}"
        OUTPUT_VARIABLE _json RESULT_VARIABLE _status OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT _status EQUAL 0)
        stm32_yml_msg(E005 "${_file}")
    endif()
    string(JSON _count ERROR_VARIABLE _invalid LENGTH "${_json}")
    if(_invalid OR NOT _count EQUAL 1)
        stm32_yml_msg(E014 "${_file}")
    endif()
    string(JSON _json GET "${_json}" 0)
    string(JSON _type TYPE "${_json}")
    if(NOT _type STREQUAL "OBJECT")
        stm32_yml_msg(E014 "${_file}")
    endif()
    set(_result "${BASE}")
    string(JSON _include_type ERROR_VARIABLE _absent TYPE "${_json}" include)
    if(NOT _absent)
        set(_includes "[]")
        if(_include_type STREQUAL "STRING")
            _stm32_yml_json_value("${_json}" include _include)
            if(NOT _include STREQUAL "\"\"")
                string(JSON _includes SET "[]" 0 "${_include}")
            endif()
        elseif(_include_type STREQUAL "ARRAY")
            string(JSON _includes GET "${_json}" include)
        elseif(NOT _include_type STREQUAL "NULL")
            stm32_yml_msg(E012 "${_file}")
        endif()
        string(JSON _length LENGTH "${_includes}")
        if(_length GREATER 0)
            math(EXPR _last "${_length} - 1")
            get_filename_component(_directory "${_absolute}" DIRECTORY)
            foreach(_index RANGE 0 ${_last})
                string(JSON _type TYPE "${_includes}" ${_index})
                string(JSON _include GET "${_includes}" ${_index})
                if(NOT _type STREQUAL "STRING" OR _include STREQUAL "")
                    stm32_yml_msg(E012 "${_file}")
                endif()
                get_filename_component(_child "${_include}" ABSOLUTE BASE_DIR "${_directory}")
                _stm32_yml_load_includes("${_child}" "${_result}" "${STACK}" _result)
            endforeach()
        endif()
        string(JSON _json REMOVE "${_json}" include)
    endif()
    _stm32_yml_merge_json("${_result}" "${_json}" "" _result)
    stm32_yml_msg(I035 "${_file}")
    set(${OUT} "${_result}" PARENT_SCOPE)
endfunction()
