"""Generate per-target configs and linker scripts from the F103 reference.

The F103 files in the fixture root are the reference: every other target gets
the same profiles with its MCU, STM32Cube package, CPU flags, FreeRTOS port,
memory layout and HAL configuration. Run after changing the reference and
commit the result:  python3 tests/firmware/semihosting/targets/make_targets.py
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
CUBE = Path('/opt/STM32Cube/Repository')
# name: MCU, Cube package, family, CPU flags, FreeRTOS port, Flash/RAM KiB, Arduino MCU_TARGET
TARGETS = {
    'f030': ('STM32F030R8T6', 'V1.11.6', 'f0', 'mcpu=cortex-m0, mthumb, mfloat-abi=soft', 'ARM_CM0', 64, 8, 'F030'),
    'f411': ('STM32F411CEU6', 'V1.28.3', 'f4', 'mcpu=cortex-m4, mthumb, mfloat-abi=soft', 'ARM_CM4F', 512, 128, 'F411'),
    'f401': ('STM32F401CCU6', 'V1.28.3', 'f4', 'mcpu=cortex-m4, mthumb, mfloat-abi=soft', 'ARM_CM4F', 256, 64, 'F401'),
    'g431': ('STM32G431CBU6', 'V1.6.3', 'g4', 'mcpu=cortex-m4, mthumb, mfloat-abi=soft', 'ARM_CM4F', 128, 32, 'G431'),
    'g474': ('STM32G474CEU6', 'V1.6.3', 'g4', 'mcpu=cortex-m4, mthumb, mfloat-abi=soft', 'ARM_CM4F', 512, 128, 'G474'),
    'f746': ('STM32F746ZGT6', 'V1.17.3', 'f7', 'mcpu=cortex-m7, mthumb, mfloat-abi=soft', 'ARM_CM7', 1024, 320, 'F746'),
}
HAL_MODULES = ('HAL_MODULE_ENABLED', 'HAL_CORTEX_MODULE_ENABLED', 'HAL_FLASH_MODULE_ENABLED',
               'HAL_GPIO_MODULE_ENABLED', 'HAL_RCC_MODULE_ENABLED', 'HAL_PWR_MODULE_ENABLED',
               'HAL_DMA_MODULE_ENABLED', 'HAL_EXTI_MODULE_ENABLED')


def hal_conf(family, cube):
    """Cube template with only the modules the fixture uses."""
    upper = family.upper()
    template = CUBE / f'STM32Cube_FW_{upper}_{cube}' / f'Drivers/STM32{upper}xx_HAL_Driver/Inc/stm32{family}xx_hal_conf_template.h'
    text = template.read_text(encoding='utf-8', errors='replace')

    def module(match):
        name = match.group(2)
        return match.group(0) if name in HAL_MODULES else f'/* {match.group(0).strip()} */'
    text = re.sub(r'^(\s*)#define\s+(HAL_\w+_MODULE_ENABLED|HAL_MODULE_ENABLED)\b.*$', module, text, flags=re.M)
    header = (f'/* Generated by make_targets.py from {template.relative_to(CUBE)}:\n'
              '   only HAL, CORTEX, FLASH, GPIO, RCC, PWR, DMA and EXTI modules enabled. */\n')
    return header + text


def main():
    config = (ROOT / 'stm32_config.yml').read_text()
    script = (ROOT / 'STM32F103C8_FLASH.ld').read_text()
    template = (ROOT / 'STM32F103C8_FLASH.ld.in').read_text()
    for name, (mcu, cube, family, cpu, port, flash, ram, arduino) in TARGETS.items():
        directory = ROOT / 'targets' / name
        directory.mkdir(parents=True, exist_ok=True)
        device = mcu[5:11]
        text = config
        text = text.replace('mcu: STM32F103C8T6', f'mcu: {mcu}')
        text = text.replace('cubefw_package: V1.8.7', f'cubefw_package: {cube}')
        text = text.replace('sources: [system_stm32f1xx.c, main.cpp]', 'sources: [main.cpp]')
        text = text.replace('system_stm32f1xx.c, ', '')
        text = text.replace('include_directories: [.]', f'include_directories: [., targets/{name}]')
        text = text.replace('linker_script: STM32F103C8_FLASH.ld',
                            f'linker_script: STM32{device}_FLASH.ld\nlinker_script_dir: targets/{name}')
        text = text.replace('mcpu=cortex-m3, mthumb, mfloat-abi=soft', cpu)
        text = text.replace('ARM_CM3', port)
        text = text.replace('mcu_target: F103', f'mcu_target: {arduino}')
        text = f'# Generated by make_targets.py from ../../stm32_config.yml for {mcu}.\n' + text
        (directory / 'stm32_config.yml').write_text(text)
        layout = (f'/* Generated by make_targets.py: {mcu} layout from the F103C8 fixture script. */',
                  f'_estack = 0x20000000 + {ram}K;',
                  f'FLASH (rx)      : ORIGIN = 0x8000000, LENGTH = {flash}K',
                  f'RAM (xrw)      : ORIGIN = 0x20000000, LENGTH = {ram}K')
        for source, target in ((script, f'STM32{device}_FLASH.ld'), (template, f'STM32{device}_FLASH.ld.in')):
            out = source.replace('/* Test-local F103C8 layout based on the generated stm32-cmake linker script. */', layout[0])
            out = out.replace('_estack = 0x20000000 + 20K;', layout[1])
            out = out.replace('FLASH (rx)      : ORIGIN = 0x8000000, LENGTH = 64K', layout[2])
            out = out.replace('RAM (xrw)      : ORIGIN = 0x20000000, LENGTH = 20K', layout[3])
            assert out.count(f'{flash}K') >= 1 and layout[1] in out
            (directory / target).write_text(out)
        (directory / f'stm32{family}xx_hal_conf.h').write_text(hal_conf(family, cube))
        print('generated', directory.relative_to(ROOT))


if __name__ == '__main__':
    main()
